hmcts/sscs-task-configuration

- src/main/resources/wa-task-types-sscs-benefit.dmn
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/DmnDecisionTable.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CaumundaTaskTypeTest.java
https://tools.hmcts.net/jira/browse/SSCS-11150
Create Task Type DMN
```
[ ] Yes
[X] No
```
> SSCS-11150 Create Task Type DMN

- config/owasp/suppressions.xml
- src/main/resources/wa-task-cancellation-sscs-benefit.dmn
- src/main/resources/wa-task-completion-sscs-benefit.dmn
- src/main/resources/wa-task-configuration-sscs-benefit.dmn
- src/main/resources/wa-task-initiation-sscs-benefit.dmn
- src/main/resources/wa-task-permissions-sscs-benefit.dmn
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskCancellationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskCompletionTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskConfigurationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskInitiationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskPermissionTest.java
https://tools.hmcts.net/jira/browse/SSCS-11112
Create Task "Review Bi-Lingual Document" for CTSC Administrator
```
[ ] Yes
[X] No
```
> SSCS-11112 Review Bi-Lingual Document

- src/main/resources/wa-task-cancellation-sscs-benefit.dmn
- src/main/resources/wa-task-completion-sscs-benefit.dmn
- src/main/resources/wa-task-configuration-sscs-benefit.dmn
- src/main/resources/wa-task-initiation-sscs-benefit.dmn
- src/main/resources/wa-task-permissions-sscs-benefit.dmn
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskCancellationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskCompletionTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskConfigurationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskInitiationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskPermissionTest.java
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
> SSCS-11126 Review Valid Appeal

- src/main/resources/wa-task-cancellation-sscs-benefit.dmn
- src/main/resources/wa-task-completion-sscs-benefit.dmn
- src/main/resources/wa-task-configuration-sscs-benefit.dmn
- src/main/resources/wa-task-initiation-sscs-benefit.dmn
- src/main/resources/wa-task-permissions-sscs-benefit.dmn
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskCancellationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskCompletionTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskConfigurationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskInitiationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskPermissionTest.java
Sscs 11129 review listing error
```
[ ] Yes
[x] No
```
> SSCS 11129 review listing error

- src/main/resources/wa-task-cancellation-sscs-benefit.dmn
- src/main/resources/wa-task-completion-sscs-benefit.dmn
- src/main/resources/wa-task-configuration-sscs-benefit.dmn
- src/main/resources/wa-task-initiation-sscs-benefit.dmn
- src/main/resources/wa-task-permissions-sscs-benefit.dmn
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskCancellationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskCompletionTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskConfigurationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskInitiationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskPermissionTest.java
> SSCS 11120 review bf date

- src/main/resources/wa-task-cancellation-sscs-benefit.dmn
- src/main/resources/wa-task-completion-sscs-benefit.dmn
- src/main/resources/wa-task-configuration-sscs-benefit.dmn
- src/main/resources/wa-task-initiation-sscs-benefit.dmn
- src/main/resources/wa-task-permissions-sscs-benefit.dmn
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskCancellationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskCompletionTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskConfigurationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskInitiationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskPermissionTest.java
Updated DMN files (initiation, permissions, configuration) and Unit test
```
[ ] Yes
[x] No
```
> SSCS 11135 create bundle and allocate case roles

- src/main/resources/wa-task-cancellation-sscs-benefit.dmn
- src/main/resources/wa-task-configuration-sscs-benefit.dmn
- src/main/resources/wa-task-initiation-sscs-benefit.dmn
- src/main/resources/wa-task-permissions-sscs-benefit.dmn
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskCancellationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskConfigurationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskInitiationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskPermissionTest.java
Updated DMN files (initiation, permissions, configuration) and Unit test
```
[ ] Yes
[x] No
```
> SSCS 11138 review outstanding draft decision required

- build.gradle
- config/owasp/suppressions.xml
- src/main/resources/wa-task-permissions-sscs-benefit.dmn
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskPermissionTest.java
https://tools.hmcts.net/jira/browse/SSCS-11892
SSCS CTSC Admin not seeing tasks on XUI
Updated role names, should be in lower case.
```
[ ] Yes
[x] No
```
> SSCS-11892 Fix role names

- build.gradle
https://tools.hmcts.net/jira/browse/SSCS-11188
Update dependency check version to allow PR to create repo in Sonarcloud.
```
[ ] Yes
[X] No
```
> Update dependency check version

- src/main/resources/wa-task-permissions-sscs-benefit.dmn
https://tools.hmcts.net/jira/browse/SSCS-11899
Removed Own permission from case-allocator and task-supervisor
```
[ ] Yes
[x] No
```
> SSCS-11899 Users could not re assign tasks

- src/main/resources/wa-task-completion-sscs-benefit.dmn
- src/main/resources/wa-task-configuration-sscs-benefit.dmn
- src/main/resources/wa-task-initiation-sscs-benefit.dmn
- src/main/resources/wa-task-permissions-sscs-benefit.dmn
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskCompletionTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskInitiationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskPermissionTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/utils/ConfigurationExpectationBuilder.java
https://tools.hmcts.net/jira/browse/SSCS-11913
Updated event id in description link. 
Fixed unit tests.
```
[ ] Yes
[x] No
```
> SSCS-11913 Review Incomplete Appeal Task completion not working

- build.gradle
- src/main/resources/wa-task-configuration-sscs-benefit.dmn
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskConfigurationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/utils/Permissions.java
https://tools.hmcts.net/jira/browse/SSCS-11939
Fix missing event links
```
[ ] Yes
[x] No
```
> Sscs 11939 fix missing events

- src/main/resources/wa-task-completion-sscs-benefit.dmn
- src/main/resources/wa-task-configuration-sscs-benefit.dmn
- src/main/resources/wa-task-permissions-sscs-benefit.dmn
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskCompletionTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskConfigurationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskPermissionTest.java
https://tools.hmcts.net/jira/browse/SSCS-11939
Removed description and auto completion events.
Updated permissions to allow manual completion.
```
[ ] Yes
[X] No
```
> SSCS-11939 Updates to reviewValidAppeal

- src/main/resources/wa-task-cancellation-sscs-benefit.dmn
- src/main/resources/wa-task-completion-sscs-benefit.dmn
- src/main/resources/wa-task-configuration-sscs-benefit.dmn
- src/main/resources/wa-task-initiation-sscs-benefit.dmn
- src/main/resources/wa-task-permissions-sscs-benefit.dmn
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskCancellationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskCompletionTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskConfigurationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskInitiationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskPermissionTest.java
https://tools.hmcts.net/jira/browse/SSCS-10383
Task configuration for writeDecisionJudge
```
[ ] Yes
[x] No
```
> SSCS-10383 Task configuration for writeDecisionJudge

- src/main/resources/wa-task-cancellation-sscs-benefit.dmn
- src/main/resources/wa-task-completion-sscs-benefit.dmn
- src/main/resources/wa-task-configuration-sscs-benefit.dmn
- src/main/resources/wa-task-initiation-sscs-benefit.dmn
- src/main/resources/wa-task-permissions-sscs-benefit.dmn
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskCancellationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskCompletionTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskConfigurationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskInitiationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskPermissionTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/utils/CancellationScenarioBuilder.java
https://tools.hmcts.net/jira/browse/SSCS-10389
Publish events and fields
```
[ ] Yes
[x] No
```
> SSCS-10389 Add configuration for prepare for hearing task

- src/main/resources/wa-task-cancellation-sscs-benefit.dmn
- src/main/resources/wa-task-completion-sscs-benefit.dmn
- src/main/resources/wa-task-configuration-sscs-benefit.dmn
- src/main/resources/wa-task-initiation-sscs-benefit.dmn
- src/main/resources/wa-task-permissions-sscs-benefit.dmn
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskCancellationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskCompletionTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskConfigurationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskInitiationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskPermissionTest.java
https://tools.hmcts.net/jira/browse/SSCS-11269
Confirm panel composition task
```
[ ] Yes
[x] No
```
> SSCS-11269 Confirm panel composition

- src/main/resources/wa-task-configuration-sscs-benefit.dmn
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskConfigurationTest.java
https://tools.hmcts.net/jira/browse/SSCS-11982
Fix completion event
```
[ ] Yes
[x] No
```
> SSCS-11982 Fix completion event

- src/main/resources/wa-task-cancellation-sscs-benefit.dmn
- src/main/resources/wa-task-initiation-sscs-benefit.dmn
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskCancellationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskInitiationTest.java
https://tools.hmcts.net/jira/browse/SSCS-11128
Added sendToDwp event to task cancellation.
Task delay should be 1 day.
```
[ ] Yes
[x] No
```
> SSCS-11128 Update reviewValidAppeal

- src/main/resources/wa-task-configuration-sscs-benefit.dmn
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskConfigurationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/utils/CaseDataBuilder.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/utils/ConfigurationExpectationBuilder.java
https://tools.hmcts.net/jira/browse/SSCS-11863
Populate region property
Fix capitalisation issue with roleCategory
```
[ ] Yes
[x] No
```
> SSCS-11863 Fix judicial tasks

- src/main/resources/wa-task-configuration-sscs-benefit.dmn
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskConfigurationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/utils/ConfigurationExpectationBuilder.java
https://tools.hmcts.net/jira/browse/SSCS-12013
Add property dueDateNonWorkingDaysOfWeek to configuration DMN.
```
[ ] Yes
[x] No
```
> Add property dueDateNonWorkingDaysOfWeek to configuration DMN

- src/main/resources/wa-task-completion-sscs-benefit.dmn
- src/main/resources/wa-task-configuration-sscs-benefit.dmn
- src/main/resources/wa-task-initiation-sscs-benefit.dmn
- src/main/resources/wa-task-permissions-sscs-benefit.dmn
- src/main/resources/wa-task-types-sscs-benefit.dmn
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskCompletionTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskConfigurationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskInitiationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskPermissionTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskTypesTest.java
SSCS-11290 Review Correction Application Task for CTSC Admin
```
[ ] Yes
[x] No
```
> SSCS 11290 create review correction application task for ctsc admin

- src/main/resources/wa-task-completion-sscs-benefit.dmn
- src/main/resources/wa-task-configuration-sscs-benefit.dmn
- src/main/resources/wa-task-initiation-sscs-benefit.dmn
- src/main/resources/wa-task-permissions-sscs-benefit.dmn
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskCompletionTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskConfigurationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskInitiationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskPermissionTest.java
> Sscs 11300

- src/main/resources/wa-task-configuration-sscs-benefit.dmn
- src/main/resources/wa-task-initiation-sscs-benefit.dmn
- src/main/resources/wa-task-permissions-sscs-benefit.dmn
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskConfigurationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskInitiationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskPermissionTest.java
> Sscs 11316

- src/main/resources/wa-task-configuration-sscs-benefit.dmn
- src/main/resources/wa-task-initiation-sscs-benefit.dmn
- src/main/resources/wa-task-permissions-sscs-benefit.dmn
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskConfigurationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskInitiationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskPermissionTest.java
> SSCS-11318 Share Remade Decision

- src/main/resources/wa-task-configuration-sscs-benefit.dmn
- src/main/resources/wa-task-initiation-sscs-benefit.dmn
- src/main/resources/wa-task-permissions-sscs-benefit.dmn
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskConfigurationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskInitiationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskPermissionTest.java
> Sscs 11514

- src/main/resources/wa-task-initiation-sscs-benefit.dmn
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskInitiationTest.java
https://tools.hmcts.net/jira/browse/SSCS-12105
Update initiation of referred tasks after tickets were updated:
SSCS-11273 - Referred by Admin TCW
SSCS-10410 - Referred to Interloc TCW
SSCS-9994 - Referred to Interloc Judge
SSCS-11259 - Referred by Admin Judge (Pre Hearing)
```
[ ] Yes
[x] No
```
> SSCS-12105 Update referred tasks

- src/main/resources/wa-task-configuration-sscs-benefit.dmn
- src/main/resources/wa-task-initiation-sscs-benefit.dmn
- src/main/resources/wa-task-permissions-sscs-benefit.dmn
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskConfigurationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskInitiationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskPermissionTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/utils/EventLink.java
https://tools.hmcts.net/jira/browse/SSCS-12099
Create task 'Review Late SOR Application and Allocate Judge'
> SSCS-12099 Review Late SOR Application and Allocate Judge

- src/main/resources/wa-task-initiation-sscs-benefit.dmn
- src/main/resources/wa-task-permissions-sscs-benefit.dmn
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/DmnDecisionTableBaseUnitTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskInitiationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskPermissionTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/utils/Permissions.java
https://tools.hmcts.net/jira/browse/SSCS-12108
Give all roles read access to all tasks.
> SSCS-12108 Read access

- src/main/resources/wa-task-initiation-sscs-benefit.dmn
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskInitiationTest.java
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
https://tools.hmcts.net/jira/browse/SSCS-12274
Correct event for task initiation
```
[ ] Yes
[ ] No
```
> SSCS-12274: Use correct event for task initiation

- src/main/resources/wa-task-cancellation-sscs-benefit.dmn
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskCancellationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskTypesTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/utils/EventLink.java
SSCS-12245
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
> TC: add check for dwpUploadResponse

- src/main/resources/wa-task-completion-sscs-benefit.dmn
- src/main/resources/wa-task-permissions-sscs-benefit.dmn
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskCompletionTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskPermissionTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskTypesTest.java
https://tools.hmcts.net/jira/browse/SSCS-12244
Added manual permissions for 'Review Robotic Failure'
```
[ ] Yes
[x] No
```
> SSCS-12244: Manual permissions for 'Review Robotic Failure'

- src/main/resources/wa-task-initiation-sscs-benefit.dmn
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskInitiationTest.java
Update intiation File
```
[ ] Yes
[x] No
```
> SSCS 11790 create additional prepare for hearing tasks

- src/main/resources/wa-task-permissions-sscs-benefit.dmn
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskPermissionTest.java
https://tools.hmcts.net/jira/browse/SSCS-12305
Fix specific access approver permissions
> SSCS-12305 Specific access approver permissions

- src/main/resources/wa-task-initiation-sscs-benefit.dmn
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskInitiationTest.java
https://tools.hmcts.net/jira/browse/SSCS-12283
Update 'Referred to Interloc' Tasks
```
[ ] Yes
[x] No
```
> SSCS-12283: 'Referred to Interloc' tasks update

- src/main/resources/wa-task-cancellation-sscs-benefit.dmn
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskCancellationTest.java
https://tools.hmcts.net/jira/browse/SSCS-12280
Removed 'interlocReviewStateAmend' from Cancellation DMN for Prepare for Hearing and Write Decision
```
[ ] Yes
[x] No
```
> SSCS-12280

- src/main/resources/wa-task-initiation-sscs-benefit.dmn
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskInitiationTest.java
https://tools.hmcts.net/jira/browse/SSCS-12281
Updated initiation dmn for 'Confirm Panel Composition' task
Fixed tests
```
[ ] Yes
[x] No
```
> SSCS-12281:  Update for 'Confirm Panel Composition' task initiation

- src/main/resources/wa-task-permissions-sscs-benefit.dmn
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskPermissionTest.java
https://tools.hmcts.net/jira/browse/SSCS-12279
[CR] Manual Cancellation Required on 'Review Postponement Request' Task
```
[ ] Yes
[ ] No
```
> SSCS-12279 - Manual Cancellation Required on 'Review Postponement Request' Task

- src/main/resources/wa-task-configuration-sscs-benefit.dmn
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskConfigurationTest.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/utils/EventLink.java
SSCS-12293
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
> add in new descs

- src/main/resources/wa-task-initiation-sscs-benefit.dmn
- src/main/resources/wa-task-types-sscs-benefit.dmn
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskInitiationTest.java
https://tools.hmcts.net/jira/browse/SSCS-12321
Update task names to include role
```
[ ] Yes
[x] No
```
> SSCS-12321: Task names update

- src/main/resources/wa-task-initiation-sscs-benefit.dmn
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskInitiationTest.java
https://tools.hmcts.net/jira/browse/SSCS-12325
Fix initiation of tasks with event hmctsResponseReviewed
> SSCS-12325 Fix confirm panel composition

- src/main/resources/wa-task-configuration-sscs-benefit.dmn
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/utils/CaseDataBuilder.java
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/utils/ConfigurationExpectationBuilder.java
https://tools.hmcts.net/jira/browse/SSCS-12343
Update task location properties, use processing venue
> SSCS-12343 Update task location properties

- src/main/resources/wa-task-initiation-sscs-benefit.dmn
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskInitiationTest.java
https://tools.hmcts.net/jira/browse/SSCS-12353
Removed actionFurtherEvidence from  "Review Urgent Hearing Request" task initiation
```
[ ] Yes
[x] No
```
> SSCS-12353: Removed actionFurtherEvidence

- src/main/resources/wa-task-completion-sscs-benefit.dmn
- src/test/java/uk/gov/hmcts/reform/sscstaskconfiguration/dmn/CamundaTaskCompletionTest.java
https://tools.hmcts.net/jira/browse/SSCS-12506
Fix type in completion event for Review Listing Error
```
[ ] Yes
[X] No
```
> SSCS-12506 Update completion event

- build.gradle
- config/owasp/suppressions.xml
Updated suppressions
Bumped spring-web and spring-expression in dependency manegement
> Dependency updates
